---
title: "PY 3155: Society, Ethics and the Law"
author: "George W. Matthews"
institute: "Plymouth State University"
date: "Fall 2020"
output:
 html_document:
  toc: no
  css: syllabus-style.css
 pdf_document: 
  latex_engine: pdflatex
  toc: no
  includes:
   in_header: "PY-3155-FA-2020-preamble.tex"
---

\thispagestyle{fancy}

***

<div class="note" markdown="1">

The theme for this version of this class is "NO JUSTICE, NO PEACE."

- What does that even mean?

- Is it a call to action or a sign of resignation?

- Does it express hope in the possibility of justice and peace or is it cynically dismissive?

- How can we be even interested in Justice and Peace with _**them**_?

</div>


## *Contact info*

<div class="infobox" markdown="1">

**Email**: this is the most reliable way to contact me. Address available on Moodle and in Outlook. 

**Virtual Office**: I'll online for this class on a regular basis. If you need to speak one on one let me know and we can arrange a suitable time.

**Phone**: Listed on course Moodle page. Please state your name if you send a text! And avoid leaving voicemail messages since Verizon tends to deliver them days after you leave them.

</div>

***

## *Online Schedule*

<div class="infobox" markdown="1">

+---------+:-------------:+:--------------:+:---------:+:-------------:+
|         | M             | T             | W          | TH            |
+=========+:=============:+:=============:+:==========:+:=============:+
| Week 1  |               | **video** \   |            | **video** \   | 
|         |               | 9:30 AM       |            | 9:30 AM       |
+---------+:-------------:+:-------------:+:----------:+:-------------:+
| Week 2  | **text** \    |               | **text** \ |               |        
|         | 6 - 7 PM      |               | 6 - 7 PM   |               |
+---------+:-------------:+:-------------:+:----------:+:-------------:+

##### *REPEATS EVERY TWO WEEKS*

</div>

## *Textbook*

<div class="note" markdown="1">

There is no textbook for this course. Required readings and other assignments are available at the [Society, Ethics and the Law course blog](http://www.6worlds.net/society-ethics-law/). We will be making extensive use of the blog in this course so please check it out and bookmark it now. In the beginning of the course there will be a workshop on how to use the blog.

</div>

<div class="infobox" markdown="1">

##### Each **section** of the course lasts **two weeks** and covers one chapter in the online text.

<br>

|     SECTION     |  Online | Justice Comments | Blog Post | Blog Comments | Project |
|:---------------:|:-------:|:----------------:|:---------:|:-------------:|:-------:|
|  1. 8/24 - 9/6  |    2    |         2        |           |       5       |         |
|  2. 9/7 - 9/20  |    2    |         2        |     1     |       7       |         |
|  3. 9/21 - 10/4 |    2    |         2        |     1     |       7       |         |
| 4. 10/5 - 10/18 |    2    |         2        |     1     |       7       |  begin  |
| 5. 10/19 - 11/1 |    2    |         2        |           |       7       |  work   |
| 6. 11/2 - 11/20 |    2    |       (2)        |  Project  |       7       |  POST   |
</div>


## *Assignments* 

<div class="assignment" markdown="1">

### Online 

- I'll be online in the video chatroom twice and in the text chatroom twice in each section of the course. You have to attend any two of these. 
- The format of both is open, although at times I'll have specific things to talk about. Do expect to participate and come prepared by having looked at some recent course material. 

*30 points*

</div>

<div class="assignment" markdown ="1">

### Justice Comments

- Every section contains 4 25 minute long lectures from Michael Sandels "Justice" course at Harvard. 
- This semester we are going to follow this lecture series as a supplement to reading the text. 
- Your assignment is to pick two of the four videos in each section and write a longish comment (300-500 words long) to it.
- Your comments can take whatever form and style you want them to.
- NOTE: you need to do 10 of these total, so you get to miss two.

*5 points each, maximum 50 points.*

</div>

<div class="assignment" markdown="1">

### Blog Posts

- Everyone in the course will be required to post three original articles to the course blog. Posting deadlines will be determined by which group you are in. See [course calendar](https://www.6worlds.net/society-ethics-law/society-ethics-and-the-law/preface/readme/) for details. 

*30 points*

</div>

<div class="assignment" markdown="1">

### Blog Comments

- These should be evenly divided between comments on your classmates' blog posts and the reading and other content listed for each section.
- These should be evenly divided between supporting, neutral and critical. Be constructive in your criticism.
- Blog posters note: you can always revise their work. Reply in a comment when you change things.
- Seven comments are due at the end of each section (five in section 1), for a total of 40 over the course of the semester.

*1 point each up to 40 points*

</div>

<div class="assignment" markdown="1">

### Action Project

- This is a project on any topic that has to do with active citizenship. 
- It can involve: building a coalition, contributing to the blog, making a documentary video, composing a photo essay.
- We'll discuss this in class.

*20 points*

</div>
## *Grades*

<div class="caution" markdown="1">

There are **170 possible points** in the course. 

  - **To pass** you need to earn **95 points** (55% of total).
  - **For a C** you need to earn **120 points** (70% of total).
  - **For a B** you need to earn **135 points** (80% of total).
  - **For an A** you need to earn **150 points** (90% of total). 
  
</div>

***

## *Accessibility*

<div class="infobox" markdown="1">

Plymouth State University is committed to providing students with documented disabilities equal access to all university programs and facilities. If you think you have a disability requiring accommodations, you should contact Campus Accessibility Services (CAS), located in Speare (535-3300) to determine whether you are eligible for such accommodations. According to University policy accommodations will only be considered for students who have registered with CAS. If you have authorized CAS to electronically deliver a Letter of Accommodations for this course, please let me know and we can work out how to meet your needs.

In addition, I have designed and chosen web-based learning material with accessibility in mind. If you find any shortcoming in this regard please let me know and I can fix things.

</div>

***

### *Catalog Course Description*

Students are tasked with analyzing how ethics and morality intersect with the criminal justice system and in turn effect society. Explores ethical theories and legal concepts, with particular attention to legal issues connected to race, class, and gender. Students are expected to apply interdisciplinary concepts in order to demonstrate their mastery of general education skills. Not open to students who have earned credits for CJ 3150. (DICO) (INCO)(INCP)

### *Course learning outcomes*

On successful completion of this course the student will be able to:

1. Describe the aim of philosophy, its major branches and how it differs from science and other cultural forms.
2. Explain and employ valid and sound reasoning.
3. Classify and describe logical fallacies and cognitive biases as they relate to reasoning about ethics.
4. Explain and analyze major philosophical approaches to ethics in terms of their claims, consequences and common arguments given in their support.
5. Critically assess philosophical arguments about real-world ethical issues. 
6. Describe and explain the major lines of argument concerning a selection of issues in applied ethics and social and political philosophy.
7. Engage in philosophical debate with their peers on a variety of topics in ethics.
8. Demonstrate proficiency in the use of online writing tools such as Wordpress.

### *ADA Statement*

Plymouth State University is committed to providing students with documented disabilities equal access to all university programs and facilities. If you think you have a disability requiring accommodations, you should contact Campus Accessibility Services (CAS), located in Speare (535-3300) to determine whether you are eligible for such accommodations. Academic accommodations will only be considered for students who have registered with CAS. If you have authorized CAS to electronically deliver a Letter of Accommodations for this course, please communicate with your instructor to review your accommodations.
