---
title: "Science or Superstition"
author: "George W. Matthews"
date: "Spring 2020"
output:
 html_document:
  toc: no
 pdf_document: 
  latex_engine: pdflatex
  toc: no
  includes:
   in_header: "PYDI-2710-SP-2020-preamble.tex"
---

\thispagestyle{fancy}
***
Office: Memorial 005

Office hours: T, TH 9-10:45 AM and by appointment

***

### *Textbook*

Readings are available at the [Science or Superstition course blog](http://www.6worlds.net/science-blog/).

***

### *Groups*

Everyone in class will be randomly assigned to a group of 3 or 4 people. These groups are for three different purposes:

1. They determine when your blog posts are due. Your blog posts are done by you alone, group membership just determines when you post.
2. You will work with your group on in-class assignments such as the Case Studies.
3. You will work with your group on the big group project described below.

***

### *Assignments*

#### **Online Participation (NEW)**

- The remainder of the semester is divided into 3 sections, each two weeks long. In each section four different topics will be offered as Zoom sessions, and there will be four hour long open text chat sessions. For the chat sessions the first two (the ones on a Tuesday) will be on anything related to the section's topics and the second two (the ones on a Thursday) will be devoted to the case study topic of that section. **To get full credit for this part of the course, each person will have to attend EITHER 3 Zoom sessions, or 2 Zoom sessions and one chat, or 1 Zoom session and 2 chats.** See course calendar for dates and topics. (5 points for each session attended: 45 points total)

#### Blog

- Everyone in the course will be required to post three original articles to the course blog. Posting deadlines will be determined by which group you are in. See [course calendar](http://www.6worlds.net/science-blog/science-or-superstition/assignments/) for details. (30 points)

#### Blog comments

- In addition to posting articles on the blog you will also be required to comment on your classmates articles 20 times over the course of the semester. (20 points)

#### Reading comments

- The course blog also contains the readings for the semester. In addition to commenting on your classmates posts, you will also have to comment 20 times on items from the reading list. (20 points)

#### Case studies

- There will be five in-class case study assignments to be completed with your group. **NOTE: case studies can now be completed alone or with a partner or two in your section or the other one if they are available.** (5 points each, total 25 points)

#### Group project

- The big group project for the semester is an extended examination in some area of "not quite science." This project will involve: establishing a group charter, keeping notes on group meetings and progress, picking a topic, investigating that topic, writing a group blog post. We will get started on this project in class. (15 points)


#### **FINAL DISCUSSION (NEW)**

- During final exam week I will hold three open discussions on Zoom. These are open discussions in which everyone should expect to participate at least a little bit. The topic of these discussions will be "Science or Superstition?" and I will explain the format as they get closer. (10 points)

***

### **Grades (REVISED)**

- There are 165 possible points in the course. 
  - To get an A you need at least 150 points
  - To get a B, B+ or A- you need between 135 and 150 points
  - To get a C, C+ or B- you need between 115 and 135 points
  - To get a D you need between 100 and 115 points
  
  #### **Pass/No-pass (NEW and OPTIONAL)**

- For those who might be concerned that the disruptions of the second half of the semester will hurt your chances of getting a good grade in  this class and that it will drag your G.P.A. down you can choose this option. If you do, you will need to get at least **100 out of the 165** possible points to pass. If you get less than that you will get a grade of no-pass. In neither case does the result affect your G.P.A. although no-pass means that you will not get credit for the course and will have to make up the 3 credits this course is worth by either taking it again or another course in its place.

- **I will send out  a survey on this option on May 1. To choose this option you'll have to answer yes on the survey. If you do not complete the survey I'll assume that you are not interested and are happy with a regular letter grade.**

***

### *Class norms*

Cell phones and laptops are useful tools but they can also be a distraction. It is expected that showing up to class means you are intending to fully participate. This means that if devices are open you shouldn't be doing non-class related things on them including working on blog posts and comments during class.

Participating in class discussions is a great way to learn as much as you can from the course so being willing to participate and not leave it up to the unofficial "spokespeople" who may step up to respond to questions is encouraged.

### *Attendance*

Class attendance is expected, especially on days when in-class activities such as case studies are scheduled. As an incentive for attending, perfect attendance (missing no classes all semester) earns 5 points extra credit, missing 1 class earns 4 points, 2 classes 3 points. 

***

### *Catalog Course Description*

Utilizes scientific methodologies to investigate, analyze, and interpret data to propose answers, offer explanations, and make predictions to philosophically analyze the power and limitations of science. Distinguishes science from irrational opinion and superstition. Explores the extent to which science is a way to knowledge, and finds philosophical principles that can guide us in evaluating controversial beliefs.

### *Course learning outcomes*

1. Utilize scientific methods to plan, investigate, collect, analyze, and interpret data to propose answers and explanations about reality.
2. Engage in significant field or lab work to study and analyze phenomena and make predictions about experiences in contemporary environments.
3. Identify the power and limitations of scientific methodologies.
4. Distinguish between science, pseudoscience, and superstition.
5. Identify philosophical principles that can guide us in evaluating controversial beliefs.
6. Distinguish between scientific reasoning and irrational opinion.

### *ADA Statement*

Plymouth State University is committed to providing students with documented disabilities equal access to all university programs and facilities. If you think you have a disability requiring accommodations, you should immediately contact the Disability Services Office (DSO) in the Center for Student Success in Mary Lyon (535-3065) to determine whether you are eligible for such accommodations. Academic accommodations will only be considered for students who have registered with DSO. If you have a Letter of Accommodation for this course from DSO, please provide the instructor with that information privately so that you and the instructor can review those accommodations.
