---
title: "PYDI 2710: Science or Superstition "
author: "George W. Matthews"
date: "Fall 2020"
output:
 html_document:
  toc: no
  css: syllabus-style.css
 pdf_document: 
  latex_engine: pdflatex
  toc: no
  includes:
   in_header: "PYDI-2710-FA-2020-preamble.tex"
---

\thispagestyle{fancy}

***

## *Contact info*

<div class="infobox" markdown="1">

**Email**: this is the most reliable way to contact me. Address available on Moodle and in Outlook. 

**Virtual Office**: I'll online for this class on a regular basis. If you need to speak one on one let me know and we can arrange a suitable time.

**Phone**: Listed on course Moodle page. Please state your name if you send a text! And avoid leaving voicemail messages since Verizon tends to deliver them days after you leave them.

</div>

***

## *Online Schedule*

<div class="infobox" markdown="1">


+---------+:-------------:+:--------------:+:---------:+:-------------:+
|         | M             | T             | W          | TH            |
+=========+:=============:+:=============:+:==========:+:=============:+
| Week 1  |               | **video** \   |            | **video** \   | 
|         |               | 11 AM - noon\ |            | 11 AM - noon\ |
|         |               | 2 PM - 3 PM   |            | 2 PM - 3 PM   | 
+---------+:-------------:+:-------------:+:----------:+:-------------:+
| Week 2  | **text** \    |               | **text** \ |               |        
|         | 7 - 8 PM \    |               | 7 - 8 PM \ |               |
|         | 8 - 9 PM      |               | 8 - 9 PM   |               |
+---------+:-------------:+:-------------:+:----------:+:-------------:+




* REPEATS EVERY TWO WEEKS *

</div>

## *Textbook*

<div class="note" markdown="1">

There is no textbook for this course. Required readings and other assignments are available at the [Science or Superstition course blog](https://www.6worlds.net/science-blog/). We will be making extensive use of the blog in this course so please check it out and bookmark it now. In the beginning of the course there will be a workshop on how to use the blog.

</div>



## *Assignments* 


<div class="infobox" markdown="1">

##### Each **section** of the course lasts **two weeks** and covers one chapter in the online text.

<br>

|     SECTION     |  Online | Reading Comments | Blog Post  | Blog Comments | Case Study | Project  |
|:---------------:|:-------:|:----------------:|:----------:|:-------------:|:----------:|:--------:|
|  1. 8/24 - 9/6  |    2    |         4        |            |               |            |          |
|  2. 9/7 - 9/20  |    2    |         4        |     1      |       4       |      1*    |          |
|  3. 9/21 - 10/4 |    2    |         4        |     1      |       4       |      2*    |          |
| 4. 10/5 - 10/18 |    2    |         4        |     1      |       4       |      3*    |  begin*  |
| 5. 10/19 - 11/1 |    2    |         4        |            |       4       |      4*    |   work*  |
| 6. 11/2 - 11/20 |    2    |         4        |  project*  |       4       |      5*    |   POST*  |

`* = work with group`

**Final Discussion** To conclude the semester we will have an online "fishbowl" discussion on the topic of "Science or Superstition?" This will take place twice on Thurday November 19, at 11 AM and then again at 2 PM.

</div>


## Work Groups

<div class="note" markdown="1">

Everyone in the class will be randomly assigned to a group of 5 (or maybe 6) students. 

- Some assignments -- the case studies and the group project are to be done with these groups.*

- Each group has its own dedicated discussion forum that can be used to coordinate group work. It is available on the Moodle home page.

</div>

## Assignment Details

<div class="assignment" markdown="1">

### Online 

- I'll be online in the video chatroom twice and in the text chatroom twice in each section of the course. You have to attend any two of these. 
- The format of both is open, although at times I'll have specific things to talk about. Do expect to participate and come prepared by having looked at some recent course material. 
- The final text chat of each section will be devoted to the case study starting in section 2.

*30 points*

</div>

<div class="assignment" markdown="1">

### Reading Comments 

- There are two parts of the blog, the static material that I post on content "pages" and your always new blog "posts." You will have to comment on both.
- Each section you should write 4 comments on any page in the relevant reading section. So if it's section 3 comment on any items the third section's reading list. 
- Please disagree, be clear and write at least 70 words in a comment! (this is 70+).

*1 point each up to 25 total*

</div>


<div class="assignment" markdown="1">

### Blog Posts

- Everyone in the course will be required to post three original articles to the course blog. Posting deadlines will be determined by which group you are in. See [course calendar](http://www.6worlds.net/science-blog/science-or-superstition/assignments/) for details. 
- Read [guidelines](https://www.6worlds.net/science-blog/science-or-superstition/chapter-1/1-1/welcome/) before posting.

*30 points*

</div>

<div class="assignment" markdown="1">

### Blog Comments

- In addition to posting articles on the blog you will also be required to comment **on your classmates articles** 25 times over the course of the semester starting in the second section.
- Again, please disagree and feel free to rsepond to responses.

*1 point each up to 20 total*

</div>

<div class="assignment" markdown="1">

### Case Studies

- These are short, directed research and reflection activities to be done with your groups. 
- Text and video chat are easily available to facilitate working as a group. We'll set this up in our first online sessions.
- These start in the second section, and are to be turned in as submitted Google forms by the end of sections 2-6.

*5 points each, 25 points total*

</div>

<div class="assignment" markdown="1">

### Final Project

- This is a collaborative research and presentation project on some area of "Not Quite Science." 
- We'll talk about possible topics, but this will involve some sort of visual presentation using some presentation tool such as Prezi, Slides, Thinglink, h5P, etc. or photo gallery, art work, video, etc. 
- The medium is up to you, but it should be embeddable in a Wordpress post (talk to me for technical assistance).

*20 points*

</div>

<div class="assignment" markdown="1">

### Final Discussion

- To conclude the semester we will meet online to settle the question, "Science or superstition?"

*10 points*

</div>
## *Grades*

<div class="caution" markdown="1">

There are **160 possible points** in the course. 

  - **To pass** you need to earn **90 points** (55% of total).
  - **For a C** you need to earn **110 points** (70% of total).
  - **For a B** you need to earn **130 points** (80% of total).
  - **For an A** you need to earn **145 points** (90% of total). 
  
</div>

***

## *Accessibility*

<div class="infobox" markdown="1">

Plymouth State University is committed to providing students with documented disabilities equal access to all university programs and facilities. If you think you have a disability requiring accommodations, you should contact Campus Accessibility Services (CAS), located in Speare (535-3300) to determine whether you are eligible for such accommodations. According to University policy accommodations will only be considered for students who have registered with CAS. If you have authorized CAS to electronically deliver a Letter of Accommodations for this course, please let me know and we can work out how to meet your needs.

In addition, I have designed and chosen web-based learning material with accessibility in mind. If you find any shortcoming in this regard please let me know and I can fix things.

</div>

***

### *Catalog Course Description*

Utilizes scientific methodologies to investigate, analyze, and interpret data to propose answers, offer explanations, and make predictions to philosophically analyze the power and limitations of science. Distinguishes science from irrational opinion and superstition. Explores the extent to which science is a way to knowledge, and finds philosophical principles that can guide us in evaluating controversial beliefs.

### *Course learning outcomes*

1. Utilize scientific methods to plan, investigate, collect, analyze, and interpret data to propose answers and explanations about reality.
2. Engage in significant field or lab work to study and analyze phenomena and make predictions about experiences in contemporary environments.
3. Identify the power and limitations of scientific methodologies.
4. Distinguish between science, pseudoscience, and superstition.
5. Identify philosophical principles that can guide us in evaluating controversial beliefs.
6. Distinguish between scientific reasoning and irrational opinion.

### *ADA Statement*

Plymouth State University is committed to providing students with documented disabilities equal access to all university programs and facilities. If you think you have a disability requiring accommodations, you should contact Campus Accessibility Services (CAS), located in Speare (535-3300) to determine whether you are eligible for such accommodations. Academic accommodations will only be considered for students who have registered with CAS. If you have authorized CAS to electronically deliver a Letter of Accommodations for this course, please communicate with your instructor to review your accommodations.
